### PR TITLE
Demo Branch Used for Testing //// DO NOT MERGE

### PR DESCRIPTION
**Pull request by AGS48353**
Testing the full pipeline 
Will close and open often

### CODE REVIEW

**Comment by AGS48353** [comment]
omg it works

**Comment by AGS48353** [comment]
Wooooo, alas it is done, I'll be shutting this PR down after everyone has seen the output.
For the presentation, I guess I'll have a fresh PR that is clean to look at.
We also have more time to edit this tool for more functionality as this is kinda a hack move(shhhhh), maybe I parsed the JSON a bit wrong, but we can talk 'bout it later.
See ya in the morning if you're reading this at the time of posting. LOL

**Comment by cragkhit** [comment]
Hey. This is amazing! Thanks everyone for the hard work. Talk to you guys soon.

**Comment by AGS48353** [comment]
Retesting Something

**Comment by AGS48353** [comment]
Private Repo Testing is breaking the Public Version

**Comment by AGS48353** [comment]
Yup, it's breaking

**Comment by AGS48353** [comment]
This was done with the Node Server

**Comment by AGS48353** [comment]
Worked on my private repo too

**Comment by AGS48353** [comment]
Testing if it works

**Comment by AGS48353** [comment]
Hmm, might be dead ?!?

**Comment by AGS48353** [comment]
oh, it works fine

**Comment by AGS48353** [comment]
getting real results

**Comment by AGS48353** [comment]
pretty hard to capture the image once the thing runs automated

**Comment by AGS48353** [comment]
Testing PullRequest

**Pull request closed without merging**
